# Generated by Django 4.0 on 2021-12-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='image/% Y/% m/% d/')),
            ],
        ),
    ]
